### ISSUE TITLE
Not working with latest HidHide release

### ISSUE THREAD

**Issue by pavel-kalmykov** [walkco/stadia-vigem#15]
Anytime I'm trying to connect the Stadia controller, I am greeted with this constant, repeated message:

![image](https://github.com/walkco/stadia-vigem/assets/9091619/9d970ab7-2ad5-4bd6-a63f-cb4b6787adf1)

This has apparently started happening after updating HidHide.

Here's my current HidHide configuration:
![image](https://github.com/walkco/stadia-vigem/assets/9091619/8c38975e-c7fb-44d4-bb59-bac2434f247e)
![image](https://github.com/walkco/stadia-vigem/assets/9091619/cb0538cc-3d57-4fe6-a074-01781f1f47e4)

If I disable the hiding, the program recognizes the controller as usual.

What could be done to fix this?

**Comment by pavel-kalmykov-razgovorov** [comment]
Sorry about the second screenshot; the first option is actually disabled (I ticked it when doing the screenshot accidentally)

**Comment by pavel-kalmykov** [comment]
I solved it by re-adding the `stadia-vigem-x64.exe` Application again. It seems like the last update messed up some paths.
