### ISSUE TITLE
Triggers as single axis

### ISSUE THREAD

**Issue by MegaMech** [walkco/stadia-vigem#2]
Is it possible to separate the trigger z-axis into two separate axis? (Stadia is capable of separate axis tried with rewasd trial in ps4 emulation mode) As a single axis if you press both triggers at the same time they cancel each other out.

**Comment by walkco** [comment]
Hi @MegaMech, the triggers are already presented as separate axes by Stadia-ViGEm on the emulated Xbox 360 controller.

If an application is still identifying a single axis, it may be that the application is preferring the virtual gamepad provided by the standard Stadia controller driver over the one provided by ViGEm. If that's the case, you can use HidHide to hide the gamepad from the Stadia controller driver from every application except Stadia-ViGEm.

**Comment by walkco** [comment]
Hi @MegaMech, do you still have an issue with the single axis? If not, I'll close this issue shortly.

**Comment by walkco** [comment]
Closing due to no response.

**Comment by MegaMech** [comment]
@walkco Tested on W10. This is me pressing the sticks individually then both at the same time.

https://user-images.githubusercontent.com/7255464/179878529-b1601311-bb18-467e-b1ef-74ef02d52e76.mp4
